# Generated by Django 6.1 on 2026-08-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='venture',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
